"""Browser-based compatibility client for user-triggered browser flows.

stoken can be generated by the browser's JS environment when a user-initiated
login flow needs compatibility help. Low-Risk Assistance Mode blocks sensitive
automation such as outreach, bulk actions, risk-control retries, and candidate
personal-data workflows before they reach this client.

Supports two modes:
  1. CDP mode: connects to user's existing Chrome via DevTools Protocol
  2. Bridge mode: delegates fetches to the user's Chrome extension channel

Headless patchright helpers still exist for isolated utility paths, but live
BOSS platform requests fail closed instead of silently falling back to headless.
"""
import sys
import time
from pathlib import Path
from types import TracebackType
from typing import Any, cast

from boss_agent_cli.api import endpoints
from boss_agent_cli.api.throttle import RequestThrottle
from boss_agent_cli.auth.browser import _DEFAULT_CDP_URL as CDP_DEFAULT_URL

HOME_URL = "https://www.zhipin.com/"
CANDIDATE_CHAT_URL = "https://www.zhipin.com/web/geek/chat"


def _sync_playwright() -> Any:
	try:
		from playwright.sync_api import sync_playwright
	except ModuleNotFoundError:
		try:
			from patchright.sync_api import sync_playwright
		except ModuleNotFoundError as exc:
			raise RuntimeError("patchright / playwright 均未安装；仅在浏览器兼容模式需要时安装该依赖") from exc
	return sync_playwright


def _is_patchright_runtime(sync_playwright: Any) -> bool:
	return str(getattr(sync_playwright, "__module__", "")).startswith("patchright.")


class RecruiterChatTabRequired(RuntimeError):
	"""招聘者操作（issue #217 修复路径）需要用户已打开 chat/index 页。

	不自动新开 tab：避免替用户改变官方页面状态或触发额外平台风险信号。
	友好做法是返回明确指引，让用户自己打开。
	"""

	def __init__(self) -> None:
		super().__init__(
			"recruiter chat tab not found in CDP Chrome — "
			"please open https://www.zhipin.com/web/chat/index in your "
			"Chrome (CDP-attached) and retry."
		)


class BrowserChannelUnavailable(RuntimeError):
	"""No safe live browser channel is available for real platform requests."""

	def __init__(self) -> None:
		super().__init__(
			"BOSS 浏览器通道不可用：无法通过 CDP 复用真实 Chrome。"
			"为保护账号，live BOSS 请求已禁止降级到 Bridge 或 headless patchright。"
			"请用 --remote-debugging-port=9229 打开真实 Chrome 后重试。"
		)

# 超时常量
_CDP_PROBE_TIMEOUT = 3           # CDP 探测 HTTP 超时（秒）
_CDP_CONNECT_TIMEOUT_MS = 10000  # CDP 握手超时，避免 Chrome 端口存在但连接挂住
_NAV_TIMEOUT_MS = 15000          # 页面导航超时（毫秒）
_HEADLESS_NETWORKIDLE_GRACE_MS = 3000  # headless 预热的额外宽限，避免卡满 30s
_BROWSER_FETCH_TIMEOUT_MS = 30000  # 页面内 fetch 超时，避免 CLI / 前端无限等待
_CDP_CHAT_PAGE_WAIT_SECONDS = 15

# macOS / Linux / Windows Chrome user data 默认路径
_CHROME_USER_DATA_CANDIDATES = [
	Path.home() / "Library/Application Support/Google/Chrome",              # macOS
	Path.home() / ".config/google-chrome",                                  # Linux
	Path.home() / "AppData/Local/Google/Chrome/User Data",                  # Windows
]


class BrowserSession:
	"""Persistent browser session that makes API calls via page.evaluate(fetch).

	Tries CDP against the user's Chrome, then Bridge. Real platform
	requests must not silently fall back to headless automation.
	"""

	def __init__(self, cookies: dict[str, Any], user_agent: str, *, delay: tuple[float, float] = (1.5, 3.0), cdp_url: str | None = None, logger: Any = None) -> None:
		self._throttle = RequestThrottle(delay)
		# patchright / BridgeClient 运行时创建；注解为 Any 让 mypy 对外部依赖放行
		self._pw: Any = None
		self._browser: Any = None
		self._context: Any = None
		self._page: Any = None
		self._cookies = cookies
		self._user_agent = user_agent
		self._started = False
		self._cdp_url = cdp_url
		self._is_cdp = False
		self._own_context = False  # 是否由我们创建的 context（需要在 close 时清理）
		self._logger = logger
		self._bridge_client: Any = None
		self._is_bridge = False
		self._raw_cdp_url: str | None = None

	def _log(self, message: str) -> None:
		"""通过注入的 logger 输出，受 --log-level 控制。"""
		if self._logger:
			self._logger.info(message)
		else:
			print(message, file=sys.stderr)

	def _ensure_started(self) -> None:
		if self._started:
			return

		if self._cdp_url:
			if self._try_raw_cdp():
				return
			raise BrowserChannelUnavailable()

		cdp_connected = False
		try:
			sync_playwright = _sync_playwright()
			self._pw = sync_playwright().start()

			# 优先：CDP 连接用户 Chrome（登录态兼容，避免 Bridge 调试扩展介入）
			if not _is_patchright_runtime(sync_playwright) and self._try_cdp():
				cdp_connected = True
				return
		except Exception as exc:
			self._log(f"[boss] CDP 探测未完成，准备尝试 Bridge：{exc}")
		finally:
			if not cdp_connected:
				self._stop_playwright_driver()

		# 第二优先：Bridge 模式（Chrome 扩展 + daemon）。仅在 CDP 不可用时使用。
		if self._try_bridge():
			return

		raise BrowserChannelUnavailable()

	def _try_raw_cdp(self) -> bool:
		if not self._cdp_url:
			return False
		try:
			ws_url = _pick_zhipin_target_ws(self._cdp_url)
		except Exception:
			try:
				_open_cdp_tab(self._cdp_url, HOME_URL)
				deadline = time.time() + _CDP_CHAT_PAGE_WAIT_SECONDS
				while time.time() < deadline:
					try:
						ws_url = _pick_zhipin_target_ws(self._cdp_url)
						break
					except Exception:
						time.sleep(0.5)
				else:
					return False
			except Exception:
				return False

		self._raw_cdp_url = self._cdp_url
		self._started = True
		self._is_cdp = True
		self._is_bridge = False
		self._log(f"[boss] Raw CDP fetch 通道就绪 ({self._cdp_url}, {ws_url})")
		return True

	def _stop_playwright_driver(self) -> None:
		if self._pw:
			try:
				self._pw.stop()
			except Exception:
				pass
			self._pw = None

	def _try_bridge(self) -> bool:
		"""尝试通过 Browser Bridge（Chrome 扩展 + daemon）连接。"""
		try:
			from boss_agent_cli.bridge.client import BridgeClient
			client = BridgeClient()
			if not client.is_running():
				return False
			if not client.is_extension_connected():
				self._log("[boss] Bridge daemon 运行中但扩展未连接")
				return False
			self._bridge_client = client
			self._started = True
			self._is_cdp = False
			self._is_bridge = True
			self._log("[boss] Bridge 模式连接成功（Chrome 扩展 + daemon）")
			return True
		except Exception:
			return False

	def _try_cdp(self) -> bool:
		"""Try connecting to user's Chrome via CDP.

		Attempts in order:
		  1. Explicit cdp_url if provided
		  2. Default http://localhost:9229 (+ auto WS fallback)
		  3. WebSocket URL from Chrome's DevToolsActivePort file
		"""
		urls_to_try = []
		if self._cdp_url:
			urls_to_try.append(self._cdp_url)
		urls_to_try.append(CDP_DEFAULT_URL)

		# 从 DevToolsActivePort 文件读取 WebSocket URL
		ws_url = self._read_devtools_active_port()
		if ws_url:
			urls_to_try.append(ws_url)

		tried: set[str] = set()
		for url in urls_to_try:
			if url in tried:
				continue
			tried.add(url)
			if self._try_connect(url):
				return True
			# HTTP URL 连接失败时，尝试从 /json/version 获取 WS URL
			if url.startswith("http"):
				ws = self._fetch_ws_url(url)
				if ws and ws not in tried:
					tried.add(ws)
					if self._try_connect(ws):
						return True
		return False

	def _try_connect(self, url: str) -> bool:
		"""Attempt a single CDP connection, reusing user's existing context.

		Reuses the first existing browser context to preserve the user's
		login state and avoid creating extra browser state. Only creates a
		new context when none exists.
		"""
		try:
			self._browser = self._pw.chromium.connect_over_cdp(
				url,
				timeout=_CDP_CONNECT_TIMEOUT_MS,
			)
			contexts = self._browser.contexts

			if contexts:
				# 复用用户现有 context 时，以用户当前浏览器里的登录态为准。
				# 不要把本地 session.enc 中可能过期的 cookies 回灌进去，
				# 否则会污染用户正在使用的真实 BOSS 登录态。
				self._context = contexts[0]
				self._own_context = False  # 非我们创建，close 时不关闭
			else:
				# 没有已存在 context，创建新的
				self._context = self._browser.new_context()
				self._own_context = True

			# 仅在自建 context 时注入保存的 cookies。
			# 对复用的用户 context，live Chrome 才是真实状态来源。
			if self._own_context and self._cookies:
				self._context.add_cookies([
					{"name": name, "value": value, "domain": ".zhipin.com", "path": "/"}
					for name, value in self._cookies.items()
				])

			self._page = self._context.new_page()
			# CDP 模式下用较长超时 + commit 级等待（避免 networkidle 卡住）
			try:
				self._page.goto(HOME_URL, wait_until="commit", timeout=_NAV_TIMEOUT_MS)
			except Exception:
				pass  # 即使导航超时，页面 JS 环境已可用
			self._started = True
			self._is_cdp = True
			reuse_label = "复用用户 context" if not self._own_context else "新建 context"
			self._log(f"[boss] CDP 连接成功 ({url})，{reuse_label}")
			return True
		except Exception:
			if self._browser:
				try:
					self._browser.close()
				except Exception:
					pass
				self._browser = None
			return False

	@staticmethod
	def _fetch_ws_url(http_url: str) -> str | None:
		"""Fetch WebSocket debugger URL from Chrome's /json/version endpoint."""
		import httpx
		try:
			resp = httpx.get(f"{http_url}/json/version", timeout=_CDP_PROBE_TIMEOUT)
			payload = resp.json()
			if not isinstance(payload, dict):
				return None
			return cast("str | None", payload.get("webSocketDebuggerUrl"))
		except (httpx.HTTPError, ValueError, KeyError):
			return None

	@staticmethod
	def _read_devtools_active_port() -> str | None:
		"""Read Chrome's DevToolsActivePort file to get WS endpoint."""
		for user_data_dir in _CHROME_USER_DATA_CANDIDATES:
			port_file = user_data_dir / "DevToolsActivePort"
			if port_file.exists():
				try:
					lines = port_file.read_text().strip().splitlines()
					if len(lines) >= 2:
						port = lines[0].strip()
						ws_path = lines[1].strip()
						return f"ws://127.0.0.1:{port}{ws_path}"
				except Exception:
					continue
		return None

	def _start_headless(self) -> None:
		"""Fallback: launch headless patchright Chromium."""
		self._browser = self._pw.chromium.launch(headless=True)
		self._context = self._browser.new_context(
			user_agent=self._user_agent,
			viewport={"width": 1280, "height": 800},
			locale="zh-CN",
			timezone_id="Asia/Shanghai",
		)
		self._own_context = True
		self._context.add_cookies([
			{"name": name, "value": value, "domain": ".zhipin.com", "path": "/"}
			for name, value in self._cookies.items()
		])
		self._page = self._context.new_page()
		self._page.goto(HOME_URL, wait_until="domcontentloaded", timeout=_NAV_TIMEOUT_MS)
		try:
			self._page.wait_for_load_state("networkidle", timeout=_HEADLESS_NETWORKIDLE_GRACE_MS)
		except Exception as e:
			# zhipin 首页常驻请求较多，headless 模式下不一定能进入 networkidle；
			# 页面 JS 环境已可用时，继续直接发起 fetch 请求更稳。
			self._log(f"[boss] headless 首页未进入 networkidle（{e}），继续直接发起请求")
		self._started = True
		self._is_cdp = False
		self._log("[boss] CDP 不可用（提示：需以 --remote-debugging-port=9229 启动 Chrome），降级到 headless patchright")

	# ── Core request via browser fetch() ─────────────────────────────

	@staticmethod
	def _is_navigation_context_error(exc: Exception) -> bool:
		message = str(exc)
		return (
			"Execution context was destroyed" in message
			or "most likely because of a navigation" in message
			or "Cannot find context with specified id" in message
		)

	def request(self, method: str, url: str, *, params: dict[str, Any] | None = None, data: dict[str, Any] | None = None) -> dict[str, Any]:
		self._ensure_started()
		self._throttle.wait()

		referer = endpoints.REFERER_MAP.get(url, f"{endpoints.BASE_URL}/")

		# Bridge 模式：通过扩展 fetch
		if self._is_bridge and self._bridge_client:
			import urllib.parse
			full_url = url
			if params:
				full_url = f"{url}?{urllib.parse.urlencode(params)}"
			result = self._bridge_client.fetch_json(
				full_url,
				method=method,
				data=data,
				referer=referer,
			)
			self._throttle.mark()
			return cast("dict[str, Any]", result)

		evaluate_script = """
			async ({method, url, params, data, referer, timeoutMs}) => {
				const controller = new AbortController();
				const timeoutId = setTimeout(() => controller.abort(), timeoutMs);
				try {
					let fetchUrl = url;
					if (params && Object.keys(params).length > 0) {
						const sp = new URLSearchParams();
						for (const [k, v] of Object.entries(params)) {
							if (v !== null && v !== undefined) sp.append(k, String(v));
						}
						fetchUrl = url + '?' + sp.toString();
					}

					const options = {
						method: method,
						credentials: 'include',
						referrer: referer,
						headers: {
							'Accept': 'application/json, text/plain, */*',
							'X-Requested-With': 'XMLHttpRequest',
						},
						signal: controller.signal,
					};

					if (method === 'POST' && data) {
						options.headers['Content-Type'] = 'application/x-www-form-urlencoded';
						const formData = new URLSearchParams();
						for (const [k, v] of Object.entries(data)) {
							formData.append(k, String(v));
						}
						options.body = formData.toString();
					}

					const resp = await fetch(fetchUrl, options);
					return await resp.json();
				} catch (e) {
					const message = e.name === 'AbortError'
						? `browser fetch timeout after ${timeoutMs}ms`
						: e.message;
					return {code: -1, message, zpData: {}};
				} finally {
					clearTimeout(timeoutId);
				}
			}
		"""
		evaluate_args = {
			"method": method,
			"url": url,
			"params": params or {},
			"data": data,
			"referer": referer,
			"timeoutMs": _BROWSER_FETCH_TIMEOUT_MS,
		}

		if self._raw_cdp_url:
			last_error: Exception | None = None
			for _ in range(3):
				try:
					result = _cdp_evaluate_in_zhipin_tab(self._raw_cdp_url, evaluate_script, evaluate_args)
					break
				except Exception as exc:
					if not self._is_navigation_context_error(exc):
						raise
					last_error = exc
					time.sleep(0.5)
			else:
				self._log(f"[boss] raw CDP browser fetch navigation retries exhausted: {last_error}")
				result = {"code": -1, "message": "Failed to fetch", "zpData": {}}
			self._throttle.mark()
			return cast("dict[str, Any]", result)

		# Playwright 模式（CDP 或 headless）
		last_error: Exception | None = None
		for _ in range(3):
			try:
				result = self._page.evaluate(evaluate_script, evaluate_args)
				break
			except Exception as exc:
				if not self._is_navigation_context_error(exc):
					raise
				last_error = exc
				try:
					self._page.wait_for_load_state("domcontentloaded", timeout=5000)
				except Exception:
					pass
				time.sleep(0.5)
		else:
			self._log(f"[boss] browser fetch evaluate navigation retries exhausted: {last_error}")
			result = {"code": -1, "message": "Failed to fetch", "zpData": {}}

		self._throttle.mark()
		return cast("dict[str, Any]", result)

	# ── Arbitrary JS evaluation (CDP-only, raw websocket) ────────────

	def evaluate_js(self, script: str, arg: Any = None) -> Any:
		"""Run JS in the user's recruiter chat tab via raw CDP websocket.

		Required for recruiter send_message (issue #217): we reach into the
		招聘者 chat page's Vue 2 instance to call geek-list.geekClick() +
		editor.sendText(). The normal BrowserSession.request fetch path can't
		do that — it runs JS in a blank tab BrowserSession owns, not in the
		user's recruiter tab.

		Why raw CDP instead of patchright: attaching patchright to another
		tab we didn't create via new_page() triggers 'Frame was detached'
		errors when that page navigates or re-renders (Vue SFC rebuilds
		frame tree). Raw CDP is a stateless RPC — we just send
		Runtime.evaluate and read the result, no session book-keeping.

		Intentionally does NOT call _ensure_started(): patchright's
		connect_over_cdp enumerates every tab's frame tree on attach, which
		can race with Vue re-renders on the recruiter page and crash the
		Node driver before we even get to our evaluate call. evaluate_js
		only needs the CDP HTTP endpoint reachable — not patchright.

		Only works in CDP mode (user has chrome://<devtools port>/json
		reachable and the recruiter chat tab open). Bridge/headless modes
		have no access to the user's Vue runtime.
		"""
		if self._is_bridge:
			raise RuntimeError("evaluate_js requires CDP mode (bridge mode has no access to user Chrome)")
		cdp_url = self._cdp_url or CDP_DEFAULT_URL
		return _cdp_evaluate_in_chat_tab(cdp_url, script, arg)

	def evaluate_js_in_zhipin_tab(self, script: str, arg: Any = None) -> Any:
		"""Run JS in an existing BOSS candidate tab via raw CDP."""
		if self._is_bridge:
			raise RuntimeError("evaluate_js_in_zhipin_tab requires CDP mode")
		cdp_url = self._raw_cdp_url or self._cdp_url or CDP_DEFAULT_URL
		return _cdp_evaluate_in_zhipin_tab(cdp_url, script, arg)

	def evaluate_js_with_chat_events(self, script: str, arg: Any = None, *, listen_ms: int = 3000) -> dict[str, Any]:
		"""Run JS in the recruiter chat tab and collect short-lived chat WS events.

		Used by recruiter send_message verification to distinguish a real chat send
		from UI-only draft mutation or suggestion traffic.
		"""
		if self._is_bridge:
			raise RuntimeError("evaluate_js_with_chat_events requires CDP mode (bridge mode has no access to user Chrome)")
		cdp_url = self._cdp_url or CDP_DEFAULT_URL
		return _cdp_evaluate_with_chat_events_in_chat_tab(cdp_url, script, arg, listen_ms=listen_ms)

	def ensure_playwright_candidate_chat_page(self) -> dict[str, Any]:
		"""Attach Playwright to the CDP Chrome only when a file input is required."""
		if self._page is not None:
			page_url = ""
			try:
				page_url = str(self._page.url or "")
			except Exception:
				page_url = ""
			return {"ok": True, "url": page_url}
		cdp_url = self._raw_cdp_url or self._cdp_url
		if not cdp_url:
			return {
				"ok": False,
				"error": "cdp_url_missing",
				"message": "缺少 CDP URL，无法准备附件上传页面。",
			}
		try:
			sync_playwright = _sync_playwright()
		except RuntimeError as exc:
			return {
				"ok": False,
				"error": "playwright_unavailable",
				"message": str(exc),
			}
		if _is_patchright_runtime(sync_playwright):
			return {
				"ok": False,
				"error": "playwright_cdp_attach_unavailable",
				"message": "当前环境只有 patchright，不能安全 attach raw CDP 选择本地附件文件。",
			}
		try:
			self._pw = sync_playwright().start()
			if not self._try_connect(cdp_url):
				self._stop_playwright_driver()
				return {
					"ok": False,
					"error": "playwright_cdp_attach_failed",
					"message": "无法 attach 到当前 CDP Chrome 来选择本地附件文件。",
				}
			self._page.goto(CANDIDATE_CHAT_URL, wait_until="domcontentloaded", timeout=_NAV_TIMEOUT_MS)
			for _ in range(15):
				try:
					ready = self._page.evaluate(
						"""() => {
							const ulc = document.querySelector('.user-list-content');
							const vueReady = !!(
								ulc &&
								ulc.__vue__ &&
								ulc.__vue__.$parent &&
								ulc.__vue__.$parent.list &&
								ulc.__vue__.$parent.list.length > 0
							);
							const domReady = !!(ulc && ulc.querySelector('li'));
							return vueReady || domReady;
						}"""
					)
					if ready:
						return {"ok": True, "url": str(self._page.url or "")}
				except Exception:
					pass
				time.sleep(1)
			page_url = ""
			page_title = ""
			try:
				page_url = str(self._page.url or "")
			except Exception:
				page_url = ""
			try:
				page_title = str(self._page.title() or "")
			except Exception:
				page_title = ""
			if "/web/user" in page_url or "登录" in page_title or "注册登录" in page_title:
				return {
					"ok": False,
					"error": "boss_chat_login_required",
					"message": "Boss CDP 登录态已失效，聊天页被重定向到登录页。请先执行 boss login --cdp，或在当前 CDP Chrome 内重新登录 BOSS。",
					"url": page_url,
					"title": page_title,
				}
			return {
				"ok": False,
				"error": "boss_chat_page_not_ready",
				"message": "Boss 聊天页未就绪，当前无法发送附件简历。请确认聊天列表已加载，或刷新 CDP 登录态后重试。",
				"url": page_url,
				"title": page_title,
			}
		except Exception as exc:
			self._stop_playwright_driver()
			return {
				"ok": False,
				"error": "playwright_cdp_attach_failed",
				"message": f"无法准备附件上传页面: {exc}",
			}

	# ── Lifecycle ────────────────────────────────────────────────────

	@property
	def is_cdp(self) -> bool:
		"""Whether this session is using CDP connection to user's Chrome."""
		return self._is_cdp

	def close(self) -> None:
		if self._is_bridge and self._bridge_client:
			try:
				self._bridge_client.close_window()
			except Exception:
				pass
			self._bridge_client = None
			self._started = False
			return

		if self._is_cdp:
			# CDP 模式：关闭我们创建的 page 和 context，不关闭用户浏览器
			if self._page:
				try:
					self._page.close()
				except Exception:
					pass
			if self._own_context and self._context:
				try:
					self._context.close()
				except Exception:
					pass
		else:
			# Headless 模式：关闭整个浏览器实例
			if self._browser:
				try:
					self._browser.close()
				except Exception:
					pass
		if self._pw:
			try:
				self._pw.stop()
			except Exception:
				pass
		self._started = False

	def __enter__(self) -> "BrowserSession":
		return self

	def __exit__(
		self,
		exc_type: type[BaseException] | None,
		exc_val: BaseException | None,
		exc_tb: TracebackType | None,
	) -> None:
		self.close()


# ─── Raw CDP helper for evaluate_js ──────────────────────────────────────

def _pick_chat_target_ws(cdp_http_url: str) -> str:
	import json as _json
	import urllib.request

	list_url = cdp_http_url.rstrip("/") + "/json"
	try:
		with urllib.request.urlopen(list_url, timeout=3) as resp:
			tabs = _json.load(resp)
	except Exception as exc:
		raise RuntimeError(f"cannot reach CDP at {list_url}: {exc}") from exc

	for t in tabs:
		if t.get("type") == "page" and "/web/chat/index" in t.get("url", ""):
			target_ws = t.get("webSocketDebuggerUrl")
			if target_ws:
				return cast("str", target_ws)
	raise RecruiterChatTabRequired()


def _pick_zhipin_target_ws(cdp_http_url: str) -> str:
	targets = _load_cdp_targets(cdp_http_url)
	chat_targets: list[dict[str, Any]] = []
	job_targets: list[dict[str, Any]] = []
	home_targets: list[dict[str, Any]] = []
	fallbacks: list[dict[str, Any]] = []
	for target in targets:
		if target.get("type") != "page":
			continue
		url = str(target.get("url") or "")
		if "zhipin.com" not in url:
			continue
		if "/web/geek/chat" in url:
			chat_targets.append(target)
		elif "/web/geek/job" in url:
			job_targets.append(target)
		elif url.rstrip("/") == HOME_URL.rstrip("/"):
			home_targets.append(target)
		else:
			fallbacks.append(target)
	for target in [*chat_targets, *job_targets, *home_targets, *fallbacks]:
		target_ws = target.get("webSocketDebuggerUrl")
		if target_ws:
			return cast("str", target_ws)
	raise RuntimeError(
		"No existing BOSS tab found. Open https://www.zhipin.com/ in this Chrome profile and retry."
	)


def _load_cdp_targets(cdp_http_url: str) -> list[dict[str, Any]]:
	import json as _json
	import urllib.request

	list_url = cdp_http_url.rstrip("/") + "/json/list"
	with urllib.request.urlopen(list_url, timeout=_CDP_PROBE_TIMEOUT) as resp:
		payload = _json.load(resp)
	if not isinstance(payload, list):
		return []
	return [item for item in payload if isinstance(item, dict)]


def _open_cdp_tab(cdp_http_url: str, url: str) -> dict[str, Any]:
	import json as _json
	import urllib.parse
	import urllib.request

	target_url = cdp_http_url.rstrip("/") + "/json/new?" + urllib.parse.quote(url, safe="")
	req = urllib.request.Request(target_url, method="PUT")
	with urllib.request.urlopen(req, timeout=_CDP_PROBE_TIMEOUT) as resp:
		payload = _json.load(resp)
	return payload if isinstance(payload, dict) else {}


def _find_candidate_chat_target(targets: list[dict[str, Any]]) -> dict[str, Any] | None:
	for target in targets:
		if target.get("type") != "page":
			continue
		url = str(target.get("url") or "")
		if "/web/geek/chat" in url:
			return target
	return None


def _find_zhipin_login_target(targets: list[dict[str, Any]]) -> dict[str, Any] | None:
	for target in targets:
		if target.get("type") != "page":
			continue
		url = str(target.get("url") or "")
		title = str(target.get("title") or "")
		if "zhipin.com" in url and ("/web/user" in url or "登录" in title or "注册登录" in title):
			return target
	return None


def ensure_candidate_chat_page_via_cdp(
	cdp_http_url: str | None = None,
	*,
	wait_seconds: float = _CDP_CHAT_PAGE_WAIT_SECONDS,
) -> dict[str, Any]:
	"""Ensure the user's CDP Chrome has a BOSS candidate chat page open.

	This is a preflight for inbound auto-reply. It only opens/navigates a tab in
	the user's CDP Chrome and never sends chat content.
	"""
	cdp_url = cdp_http_url or CDP_DEFAULT_URL
	try:
		targets = _load_cdp_targets(cdp_url)
	except Exception as exc:
		return {
			"ok": False,
			"status": "cdp_unavailable",
			"code": "CDP_UNAVAILABLE",
			"message": f"cannot reach CDP at {cdp_url.rstrip('/')}/json/list: {exc}",
			"recoverable": True,
			"recovery_action": "用 --remote-debugging-port=9229 打开真实 Chrome 后重试",
		}

	chat_target = _find_candidate_chat_target(targets)
	if chat_target is not None:
		return _candidate_chat_ready_payload(cdp_url, chat_target, opened=False)

	try:
		_open_cdp_tab(cdp_url, CANDIDATE_CHAT_URL)
	except Exception as exc:
		return {
			"ok": False,
			"status": "open_failed",
			"code": "CDP_CHAT_PAGE_OPEN_FAILED",
			"message": f"failed to open BOSS chat page through CDP: {exc}",
			"recoverable": True,
			"recovery_action": "确认 Chrome CDP 可访问后重试，或手动打开 BOSS 聊天页",
		}

	deadline = time.time() + max(wait_seconds, 0)
	while True:
		try:
			targets = _load_cdp_targets(cdp_url)
		except Exception as exc:
			return {
				"ok": False,
				"status": "cdp_unavailable",
				"code": "CDP_UNAVAILABLE",
				"message": f"cannot reach CDP at {cdp_url.rstrip('/')}/json/list: {exc}",
				"recoverable": True,
				"recovery_action": "用 --remote-debugging-port=9229 打开真实 Chrome 后重试",
			}

		chat_target = _find_candidate_chat_target(targets)
		if chat_target is not None:
			return _candidate_chat_ready_payload(cdp_url, chat_target, opened=True)

		login_target = _find_zhipin_login_target(targets)
		if login_target is not None:
			return {
				"ok": False,
				"status": "auth_required",
				"code": "AUTH_EXPIRED",
				"message": "Boss CDP 登录态已失效，聊天页被重定向到登录页。请在当前 CDP Chrome 内重新登录 BOSS。",
				"recoverable": True,
				"recovery_action": "在当前 CDP Chrome 内重新登录 BOSS 后重试",
				"url": str(login_target.get("url") or ""),
				"title": str(login_target.get("title") or ""),
				"cdp_url": cdp_url,
			}

		if time.time() >= deadline:
			break
		time.sleep(min(1.0, max(0.1, deadline - time.time())))

	return {
		"ok": False,
		"status": "not_ready",
		"code": "CDP_CHAT_PAGE_NOT_READY",
		"message": "Boss 聊天页未在 CDP Chrome 中就绪。请确认 BOSS 页面可访问并已登录。",
		"recoverable": True,
		"recovery_action": "手动打开 https://www.zhipin.com/web/geek/chat 后重试",
		"cdp_url": cdp_url,
	}


def _candidate_chat_ready_payload(cdp_url: str, target: dict[str, Any], *, opened: bool) -> dict[str, Any]:
	return {
		"ok": True,
		"status": "ready",
		"opened": opened,
		"url": str(target.get("url") or ""),
		"title": str(target.get("title") or ""),
		"cdp_url": cdp_url,
	}


def _build_eval_expression(script: str, arg: Any) -> str:
	import json as _json

	if arg is not None:
		return f"({script})({_json.dumps(arg, ensure_ascii=False)})"
	return script


def _carve_utf8_bits(bs: bytes) -> list[str]:
	out: list[str] = []
	i = 0
	while i < len(bs):
		for length in range(min(len(bs) - i, 240), 4, -1):
			try:
				text = bs[i : i + length].decode("utf-8")
			except UnicodeDecodeError:
				continue
			if len(text) >= 5 and all(ch.isprintable() or ch in "\n\r\t" for ch in text):
				out.append(text)
				i += length
				break
		else:
			i += 1
	return out

def _cdp_evaluate_in_chat_tab(cdp_http_url: str, script: str, arg: Any) -> Any:
	"""Send Runtime.evaluate to the BOSS recruiter chat tab via raw CDP.

	Bypasses patchright entirely — avoids 'Frame was detached' errors when
	the Vue page re-renders during our call. Wraps the caller's script as
	`(fnSrc)(arg)` when arg is provided, so the script can be a JS expression
	that evaluates to a function of one argument (mirrors patchright's
	`page.evaluate(script, arg)` contract used by the PoC).
	"""
	import json as _json

	import websockets.sync.client as _ws_client

	target_ws = _pick_chat_target_ws(cdp_http_url)
	expression = _build_eval_expression(script, arg)

	with _ws_client.connect(target_ws, max_size=8 * 1024 * 1024) as ws:
		ws.send(_json.dumps({
			"id": 1,
			"method": "Runtime.evaluate",
			"params": {
				"expression": expression,
				"returnByValue": True,
				"awaitPromise": True,
			},
		}))
		deadline = time.time() + 30.0
		while time.time() < deadline:
			raw = ws.recv(timeout=max(0.1, deadline - time.time()))
			msg = _json.loads(raw)
			if msg.get("id") != 1:
				continue
			err = msg.get("error")
			if err:
				raise RuntimeError(f"CDP Runtime.evaluate error: {err}")
			result = msg.get("result", {}).get("result", {})
			if "value" in result:
				return result["value"]
			# Exception in JS side
			exc_details = msg.get("result", {}).get("exceptionDetails")
			if exc_details:
				raise RuntimeError(f"JS exception: {exc_details.get('text')} — {exc_details.get('exception', {}).get('description', '')[:300]}")
			return result
		raise RuntimeError("CDP Runtime.evaluate timed out after 30s")


def _cdp_evaluate_in_zhipin_tab(cdp_http_url: str, script: str, arg: Any) -> Any:
	import json as _json

	import websockets.sync.client as _ws_client

	target_ws = _pick_zhipin_target_ws(cdp_http_url)
	expression = _build_eval_expression(script, arg)

	with _ws_client.connect(target_ws, max_size=8 * 1024 * 1024) as ws:
		ws.send(_json.dumps({
			"id": 1,
			"method": "Runtime.evaluate",
			"params": {
				"expression": expression,
				"returnByValue": True,
				"awaitPromise": True,
			},
		}))
		deadline = time.time() + 30.0
		while time.time() < deadline:
			raw = ws.recv(timeout=max(0.1, deadline - time.time()))
			msg = _json.loads(raw)
			if msg.get("id") != 1:
				continue
			err = msg.get("error")
			if err:
				raise RuntimeError(f"CDP Runtime.evaluate error: {err}")
			result = msg.get("result", {}).get("result", {})
			if "value" in result:
				return result["value"]
			exc_details = msg.get("result", {}).get("exceptionDetails")
			if exc_details:
				raise RuntimeError(
					f"JS exception: {exc_details.get('text')} — "
					f"{exc_details.get('exception', {}).get('description', '')[:300]}"
				)
			return result
		raise RuntimeError("CDP Runtime.evaluate timed out after 30s")


def _cdp_evaluate_with_chat_events_in_chat_tab(
	cdp_http_url: str, script: str, arg: Any, *, listen_ms: int
) -> dict[str, Any]:
	import base64 as _base64
	import json as _json

	import websockets.sync.client as _ws_client

	target_ws = _pick_chat_target_ws(cdp_http_url)
	expression = _build_eval_expression(script, arg)

	with _ws_client.connect(target_ws, max_size=8 * 1024 * 1024) as ws:
		ws.send(_json.dumps({"id": 1, "method": "Network.enable"}))
		ws.send(_json.dumps({
			"id": 2,
			"method": "Runtime.evaluate",
			"params": {
				"expression": expression,
				"returnByValue": True,
				"awaitPromise": True,
			},
		}))

		events: list[dict[str, Any]] = []
		eval_value: Any = None
		eval_done = False
		deadline = time.time() + 30.0
		listen_deadline: float | None = None

		while True:
			now = time.time()
			if eval_done and listen_deadline is not None and now >= listen_deadline:
				return {"value": eval_value, "events": events}
			if now >= deadline:
				raise RuntimeError("CDP Runtime.evaluate timed out after 30s")

			timeout = 0.1 if eval_done and listen_deadline is not None else max(0.1, deadline - now)
			try:
				raw = ws.recv(timeout=timeout)
			except TimeoutError:
				continue

			msg = _json.loads(raw)
			msg_id = msg.get("id")
			if msg_id == 2:
				err = msg.get("error")
				if err:
					raise RuntimeError(f"CDP Runtime.evaluate error: {err}")
				result = msg.get("result", {}).get("result", {})
				exc_details = msg.get("result", {}).get("exceptionDetails")
				if exc_details:
					raise RuntimeError(
						f"JS exception: {exc_details.get('text')} — "
						f"{exc_details.get('exception', {}).get('description', '')[:300]}"
					)
				eval_value = result.get("value", result)
				eval_done = True
				listen_deadline = time.time() + (listen_ms / 1000.0)
				continue

			method = msg.get("method")
			if method not in ("Network.webSocketFrameSent", "Network.webSocketFrameReceived"):
				continue
			frame = msg.get("params", {}).get("response", {})
			if frame.get("opcode") not in (1, 2):
				continue

			payload_data = frame.get("payloadData", "")
			try:
				bs = _base64.b64decode(payload_data, validate=False)
			except Exception:
				bs = payload_data.encode("utf-8", errors="ignore")
			if len(bs) < 30:
				continue

			events.append({
				"ts": time.time(),
				"kind": "ws_send" if method.endswith("Sent") else "ws_recv",
				"bytes": len(bs),
				"utf8_bits": _carve_utf8_bits(bs)[:10],
			})
